### PR TITLE
Added Templates for issue and pull request

### PR DESCRIPTION
**Pull request by ms10398**
Fixed https://github.com/fossasia/susi_firefoxbot/issues/11

### CODE REVIEW

**Comment by tstreamDOTh** [comment]
@ms10398  The template for issue looks fine. For the pull request template please refer to the chat.susi.ai repo (https://github.com/fossasia/chat.susi.ai) and make the necessary changes.

**Comment by ms10398** [comment]
Is it okay now @tstreamDOTh

**Comment by tstreamDOTh** [comment]
@ms10398 Please use the same template for both issue and pull request used in https://github.com/fossasia/chat.susi.ai

**Comment by ms10398** [comment]
Now is it okay @tstreamDOTh

**Comment by tstreamDOTh** [comment]
@ms10398  For pull request make these changes. Rest is fine.
screen shot 2017-09-27 at 11 56 05 am

**Comment by ms10398** [comment]
I didnt add demo link because its a extension and it would not be deployed and have a demo link I dont think it would be relevant @tstreamDOTh

**Comment by mariobehling** [comment]
@tstreamDOTh Please approve PR. The goal is, that two people approve each PR. So, a third person can merge it. We hope to ensure the quality of commits this way.

**Comment by ms10398** [comment]
Is it okay now @tstreamDOTh

**Comment by mariobehling** [comment]
Ok, so let's get more people on board who can help to review PRs. Cheers!

**Comment by tstreamDOTh** [comment]
@hkedia321 Please help in reviewing the PRs.

**Comment by hkedia321** [comment]
@tstreamDOTh Sure I will help.

**Pull request merged**
