### PR TITLE
Fix #70 - Added option for custom server

### LINKED ISSUE #70: Option for custom server
**Actual Behaviour**

No option for setting custom server

**Expected Behaviour**

Add custom server option

**Steps to reproduce it**

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by djmgit**
Fixes issue #70, Added option for custom server in settings page.

### CODE REVIEW

**Comment by djmgit** [comment]
@tstreamDOTh I noticed your last comment on this issue #70 after making this PR, just thought of working on this as the issue had been opened for quite some time. Please review this PR, I guess it will solve the purpose of custom server as of now :)

**Comment by tstreamDOTh** [comment]
@djmgit I had clearly mentioned that it is being kept on hold since there is a lack of clarity on how its being implemented in the webchat. I have already worked on this but I am unable to test it because of some bugs which out of the scope of firefoxbot.

**Comment by tstreamDOTh** [comment]
@hkedia321 Please review

**Comment by tstreamDOTh** [comment]
@hkedia321 Had the same issue. Then let's keep this on hold until we find a way to test it and verify the results

**Pull request closed without merging**
