### PR TITLE
chatbot.html: Add hyperlink

### LINKED ISSUE #34: Add hyperlink to https://susi.ai/
**Actual Behaviour**
On clicking the SUSI logo no action takes place.

**Expected Behaviour**
On clicking the SUSI logo the user must be redirected to https://susi.ai/

**Would you like to work on the issue?**
No

### PR DESCRIPTION
**Pull request by divyam3897**
Add hyperlink to susi.ai on clicking SUSI logo.
Fixes #34

### CODE REVIEW

**Comment by tstreamDOTh** [comment]
@divyam3897 Follow the best practices. Use appropriate commit name & use the PR template. Also, the issue was claimed by another member @ms10398 . Check before working on any issue.

**Comment by divyam3897** [comment]
@tstreamDOTh thanks for the reply, I use http://chris.beams.io/posts/git-commit/ for the commit message and the issue was not assigned so I claimed it.

**Comment by tstreamDOTh** [comment]
@divyam3897 At Fossasia we follow this https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/ . Also, you did not claim it and made the PR directly. This is not encouraged. Please read through the given link before contributing.

**Comment by divyam3897** [comment]
ah, sorry for it. I will go through it. Regarding this issue should I fix the commit message and other things now or should I leave it for @ms10398 and close my PR? :)

**Comment by tstreamDOTh** [comment]
@divyam3897 No problem. Take care next time and since it's a small issue I am approving yours and @ms10398 is already working on another issue, so I guess this can be excused but in future please claim before you start.

**Comment by divyam3897** [comment]
will do surely @tstreamDOTh , thanks :)

**Pull request merged**
