### PR TITLE
Fix issue #37 - fix the lag when popup is opened

### PR DESCRIPTION
**Pull request by nifey**
Fixes issue #37 

#### Changes proposed in this pull request:
* add function loadMoreMessages that checks if the user has scrolled to the top and loads older messages.
* add variable numberOfMessagesToLoad that gives the number of messages to load initially and each time the user scrolls up.

### CODE REVIEW

**Comment by nifey** [comment]
Thanks for the suggestion @hkedia321 . I will make the changes and give a PR soon.

**Comment by nifey** [comment]
I have made the changes. @hkedia321 Please review the changes.

**Comment by tstreamDOTh** [comment]
@nifey Resolve the conflicts, @hkedia321 Approve if it looks good to you.

**Comment by hkedia321** [comment]
@nifey please resolve the conflicts. Otherwise, it looks good. I cannot test the RSS response since the response is not coming from the server. @tstreamDOTh

**Comment by nifey** [comment]
I have resolved the conflicts. 
And yes I too searched for a query that returns RSS type but couldn't find any.

**Comment by nifey** [comment]
Wait ,please don't merge this.
I am experiencing a theme issue. The dark theme is not applied even though it is set to dark. 
Anyone else experiencing this issue.

**Comment by nifey** [comment]
I found the issue. The restoreMessages function initializes all map-divs. Since the number of messages being loaded is limited to 15 initially, the older messages containing the map-div are not present. 
So trying to initialize map in a div that is not yet loaded returns an error (Which causes the theme glitch).
I'm sorry. I should have checked this before pushing. 
I will fix this soon.

**Comment by nifey** [comment]
Fixed the issue. 
Now map loads normally and the theme is applied as normal.
map

**Pull request merged**
