### PR TITLE
Fix-129 Adding Voice Output

### LINKED ISSUE #129: Adding Voice Output
**Would you like to work on the issue?**

YEs

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #129

### CODE REVIEW

**Comment by sk9331657** [comment]
@tstreamDOTh  Yes, this is by default similar to chrome bot. I will create a new pr which will add more functionalities to toggle voice output. Till then this can be merged :smile: .

**Comment by sk9331657** [comment]
@hkedia321  Please review.

**Comment by sk9331657** [comment]
@tstreamDOTh  @hkedia321  Please review this.

**Comment by sk9331657** [comment]
@hkedia321 Susi Chrome bot also has by default no option to turn off voice output.

**Comment by tstreamDOTh** [comment]
I think we need to put more thought into this. Closing this for now

**Pull request closed without merging**
