### PR TITLE
Adding Button to toggle theme similar to SUSI Chromebot. #118

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]

#### Changes proposed in this pull request:
-  Adding button to toggle theme.
#### Screenshots for the change: 
screenshot from 2018-10-15 17-02-02
screenshot from 2018-10-15 17-02-05
screenshot from 2018-10-15 17-02-33

### CODE REVIEW

**Comment by sk9331657** [comment]
@marvin08  @ms10398 Please review.

**Comment by sk9331657** [comment]
@ParthS007  Please review.

**Comment by tstreamDOTh** [comment]
I do feel the same @hkedia321 
This really is not adding much value. The idea is to keep all the settings at one place

**Comment by sk9331657** [comment]
@hkedia321 @tstreamDOTh This PR will make uniformity among both chromebot and firefoxbot . Firefixbot is lagging chromebot

**Pull request closed without merging**
