### PR TITLE
Add autofocus when extension pops up

### PR DESCRIPTION
**Pull request by ms10398**
Fixed issue https://github.com/fossasia/susi_firefoxbot/issues/9

#### Changes proposed in this pull request:
- Autofocus when extension opens

### CODE REVIEW

**Comment by ms10398** [comment]
Welcome!!
Always Happy to contribute

**Comment by hkedia321** [comment]
@ms10398  The changes are good. But please follow the best practices of naming your commits.  Please refer https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/. Thanks

**Comment by ms10398** [comment]
Do i need to change anything in it.

**Comment by hkedia321** [comment]
Yes, you can amend your commit message and push again. But please make sure you push only one commit in one PR unless it's a very big feature being implemented. Do read the best practices https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/. Thanks

**Comment by ms10398** [comment]
I will ammend the commit message and squash them to only one commit @hkedia321

**Pull request merged**
