### PR TITLE
Fix-132 Adding Login And Logout Option inside dropdown menu

### LINKED ISSUE #132: Adding Login And Logout Option inside dropdown menu
**Actual Behaviour**
Currently, user goes to the extension page to log in and log out using the settings option. Instead, there will be two option login and log out depending upon the user is logged in or not.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by sk9331657**
Fixes #132

#### Changes proposed in this pull request:
- Adding Login And Logout Option inside drop down menu

### CODE REVIEW

**Comment by sk9331657** [comment]
@Akshat-Jain  @tstreamDOTh   Please review .

**Comment by sk9331657** [comment]
@hkedia321  @tstreamDOTh  Done.

**Comment by tstreamDOTh** [comment]
@sk9331657 Build is failing, Please check

**Comment by sk9331657** [comment]
@tstreamDOTh  Ready to be merged.

**Comment by sk9331657** [comment]
@tstreamDOTh  @akshatnitd Please merge this also.

**Comment by tstreamDOTh** [comment]
@hkedia321 Please review

**Comment by sk9331657** [comment]
@hpdang  @hkedia321  @tstreamDOTh  Please review.

**Comment by sk9331657** [comment]
@tstreamDOTh  Please merge this.

**Comment by neeraj3029** [comment]
Login, logout buttons are not functioning, @sk9331657 you can solve it refer to issue #144 as well.

**Pull request merged**
