### PR TITLE
Fix #91 - Added feature to copy selected text into susi.

### LINKED ISSUE #91: Add feature which allows user to directly copy a selected word into susi and open susi
Presently there is only one context menu that directly searches a selected word. Although it is a great utility, still user might want to simply automatically copy a selected word into susi input field and then edit and finalise the query. This saves the user from typing large words and also editing the query before asking susi to get answer. For example if there is a word on the page 'neural-networks', user might want to search creator of neural networks, in that case using this feature he/she will be able to copy the word into susi (using context option), susi panel would automatically open and then he/she could type in the remaining query.

### PR DESCRIPTION
**Pull request by djmgit**
Fixes issue #91, added feature to copy selected word into susi using
context option.

### CODE REVIEW

**Comment by djmgit** [comment]
@tstreamDOTh  Please review

**Comment by hkedia321** [comment]
> I find this irrelevant, what is the use case? Why won't a user just copy-paste directly if the user wants to modify the text.
Agreed. It is unnecessary to have both the options.

**Comment by djmgit** [comment]
In case of copy and paste, user will have to copy the text, open the popup, paste it, then edit it, however in this way, he/she need not have to copy paste, rather simply use the context menu to automatically open the panel and find their word already present in the input field, all the user needs to do now is edit or add something.

**Comment by tstreamDOTh** [comment]
@djmgit Context menu is no magic. It is simply giving an option to perform an action over the selected text. In your case you are giving an option to copy paste the text essentially. It looks like an overkill.

**Pull request closed without merging**
