### PR TITLE
Add default_icon as an svg icon

### PR DESCRIPTION
**Pull request by rupav**
add icon in svg format

Fixes issue #7 

#### Changes proposed in this pull request:
- Added an svg icon which gets scaled up directly in different platforms. 

#### Demo Link: 
[Add here the link where your changes can be seen]

#### Screenshots for the change: 
Note the icon changed.
Icon had to be changed unlike earlier for svg format.

PS: Earlier icon had white 'S' written on blue background. But I could not find this type of icon in svg format. 
So I used [https://susi.ai/assets/images/susi-logo-original.svg](url) ,INKSCAPE to make the required changes.
Also sizes added in "icons" keys are recommended in one of the tutorial I watched of Udacity.

### CODE REVIEW

**Comment by rupav** [comment]
Hi @tstreamDOTh  I followed your suggested link, [https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/icons](url) .  Found that svg will be the best solution, so created one. Please review :).

**Comment by rupav** [comment]
@tstreamDOTh Please provide me a screenshot when dark theme is used . Actually the problem is I am not able to find svg image of required background. I would like to find the other way around with the dark theme if possible. Thanks.

**Comment by rupav** [comment]
@tstreamDOTh how do you want me to optimize the svg? Also [https://jakearchibald.github.io/svgomg/](url) is not helping me getting even uploading that svg file.

**Comment by tstreamDOTh** [comment]
@rupav Background is not an issue. Just use the given link to paste the markup and you will get an optimized svg. The current svg has a lot of unnecessary meta tags. Lets keep it clean.

**Comment by tstreamDOTh** [comment]
@rupav use the svg code from here https://paste.ubuntu.com/25634589/

**Comment by rupav** [comment]
Hi @tstreamDOTh  your svg code is not reproducing the required icon. 


Also INKSCAPE is not showing it correctly, minimizing the height and width of the icon is not helping too.

**Comment by tstreamDOTh** [comment]
@rupav Just embed it and check if its visible in the browser toolbar.

**Comment by tstreamDOTh** [comment]
@rupav try this https://paste.ubuntu.com/25634693/ I hope this works.

**Comment by rupav** [comment]
@tstreamDOTh Your previous svg code worked :) when embeded that. I will submit the changes then :)

**Comment by rupav** [comment]
Thank you so much @hkedia321 @tstreamDOTh. But can you help me in this, why Its 3 commits written on this pull request, although what I did is:
- git fetch upstream
- git pull upstream/master
- git add (those 2 changed files)
- git commit(those 2 changed files)
- git rebase -i HEAD~2 (for squashing them into 1 commit)
- git push origin.

But still it was showing 3 commits. What could have gone wrong. Learning git.

**Comment by tstreamDOTh** [comment]
@rupav Not the right place to discuss. DM me I will help you out.

**Pull request merged**
