### PR TITLE
Support map and anchor type of responses - fixes #27

### LINKED ISSUE #27: Support for map type of response from server
**Actual Behaviour**

When the server sends a response to display a map, no map is shown.

**Expected Behaviour**

Read and show the map response from the server

**Would you like to work on the issue?**

Yes.
(Any suggestions on how to implement this would be great)

### PR DESCRIPTION
**Pull request by hkedia321**
Fixes issue #27 

#### Changes proposed in this pull request:
- Add map from leaflet library
- Get user's location and send to server
- Support anchor type of response
- Sync map with browser history
- Add appropriate permissions in manifest file

#### Screenshots for the change: 
screenshot from 2017-10-07 19-31-39

(Please clear cache before testing this)

### CODE REVIEW

**Comment by nifey** [comment]
When we ask "where is America" the add on shows a map with the marker text "I am here". Wouldn't it be more apt if the marker text is just "Here" instead of "I am here". This is not a big issue though.

I am asking this because if it needs change, then I can change before giving a PR for #58 .

**Comment by hkedia321** [comment]
@nifey I tried following the standards set by the Susi web chat. There it says the same. If you want to change it, then please go ahead and create an Issue!

**Comment by nifey** [comment]
When we type "where is America" the add on shows a map with the marker text "I am here". Wouldn't it be more apt to have the marker text be "Here" instead of "I am here". This is not a big issue though.

I am asking this because if this needs change, I can make changes before giving a PR for #58 .

**Comment by nifey** [comment]
ok @hkedia321 , I'll create an issue.

**Pull request merged**
