### PR TITLE
Added Theme switch button

### LINKED ISSUE #118: Adding Button to toggle theme similar to  SUSI Chromebot.
**Actual Behaviour**

Currently,user have to go settings to change theme instead we can use the toggle button similar chrome bot. 

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by NishithP2004**
Fixes #118 

#### Changes proposed in this pull request:
- Added theme switch button as in Chromebot.

#### Demo Link: 
[Add here the link where your changes can be seen]

### CODE REVIEW

**Review by pranav1698 — CHANGES_REQUESTED** [review]
Please follow the instructions given in pr template more carefully
Provide a demo link
Also follow the contribution guidelines

**Comment by NishithP2004** [comment]
@pranav1698 Could you suggest any way to provide a demo link..

**Comment by pranav1698** [comment]
susi uses surge

**Comment by pranav1698** [comment]
susi uses surge

**Comment by NishithP2004** [comment]
@pranav1698 Should I `cd src` to deploy it with surge.

**Comment by NishithP2004** [comment]
@pranav1698 I did as suggested but it’s not working.

**Comment by pranav1698** [comment]
You can find the instructions in the readme file for web hosting

**Comment by NishithP2004** [comment]
> You can find the instructions in the readme file for web hosting

I had done it and my link is 
http://tacky-muscle.surge.sh/ but the link is empty.

**Comment by pranav1698** [comment]
Refer readme file it is a mozilla addon

**Comment by NishithP2004** [comment]
[susi_chatbot-1.0.zip](https://github.com/fossasia/susi_firefoxbot/files/2781596/susi_chatbot-1.0.zip)

**Comment by NishithP2004** [comment]
@pranav1698 Please check it

**Comment by pranav1698** [comment]
@NishithP2004 you need to share the signed version of the add-on not the zip File

**Review by pranav1698 — COMMENTED** [review]
@NishithP2004 you need to share the signed version of the add-on not the zip File

**Comment by NishithP2004** [comment]
@pranav1698 I’m not able to sign it as it says a similar add on is available and hence error.

**Comment by NishithP2004** [comment]
@Orbiter @mariobehling Please review

**Review by pranav1698 — COMMENTED** [review]
@NishithP2004 you can check these links: https://support.mozilla.org/en-US/kb/unable-install-add-ons-extensions-or-themes
https://support.mozilla.org/en-US/kb/cannot-remove-add-on-extension-or-theme
https://support.mozilla.org/en-US/questions/1101877
We can help you to sign add-ons but we need to test it to aproove the pr

**Pull request closed without merging**
