### PR TITLE
Add support for image

### PR DESCRIPTION
**Pull request by ms10398**
Fix https://github.com/fossasia/susi_firefoxbot/issues/40

#### Changes proposed in this pull request:
- Showing image in the chat

#### Screenshots for the change: 

firefoxwo

### CODE REVIEW

**Comment by ms10398** [comment]
@tstreamDOTh @hkedia321  I have fixed travis errors. Please have a look at it.

**Comment by ms10398** [comment]
@tstreamDOTh Can you tell me a example query so that I can work on it
Example query for Susi API and a bit more explanation for it

**Comment by tstreamDOTh** [comment]
@ms10398 The image can be part of the response. So replace the image link with appropriate tags like how it was being done for the hyperlinks instead of having a seperate function

**Comment by ms10398** [comment]
Can you please help me by telling a query for the susi api so that I can check it. Any query which has Text and image at the same time.

**Comment by tstreamDOTh** [comment]
There is no message type of "image". Logically it is wrong to have a seperate function. Make it a part of createSusiMessageAnswer function.

**Comment by ms10398** [comment]
I approached at making the program modular then writing all code in a single function can make it difficult to read. Yes there is no message type of image but logically image is a different type of reponse than a plain answer. Whats your thought @hkedia321 @tstreamDOTh @mariobehling

**Comment by ms10398** [comment]
I will try to implment it that way as there was only one case in which it can only be image when the action was answer and the expression was a link(which makes my code pass all cases). I will replace it with regex no issues.

**Comment by tstreamDOTh** [comment]
@ms10398 Made the changes?

**Comment by tstreamDOTh** [comment]
@ms10398 Any updates?

**Pull request closed without merging**
